-- MySQL Script generated by MySQL Workbench
-- 01/08/16 11:13:00
-- Model: palautedb    Version: 0.0.1
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema palautedb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema palautedb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `palautedb` DEFAULT CHARACTER SET utf8 ;
USE `palautedb` ;

-- -----------------------------------------------------
-- Table `palautedb`.`Vikailmoitus`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `palautedb`.`Vikailmoitus` (
  `idPalautelomake` INT NOT NULL AUTO_INCREMENT,
  `idTila` INT NOT NULL,
  `idKayttaja` INT NULL,
  `Aika` DATE NULL,
  `Aikaleima` DATE NOT NULL,
  `Kuvaus` MEDIUMTEXT NULL,
  `IlmoituksenTila` VARCHAR(45) NULL,
  `Korjattu` TINYINT(1) NULL,
  `ViimeksiTallentanut` VARCHAR(45) NULL,
  PRIMARY KEY (`idPalautelomake`),
  UNIQUE INDEX `idPalautelomake_UNIQUE` (`idPalautelomake` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `palautedb`.`Palautelomake`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `palautedb`.`Palautelomake` (
  `idPalautelomake` INT NOT NULL,
  `idTila` INT NOT NULL,
  `idKayttaja` INT NOT NULL,
  `Lukitus` TINYINT(1) NULL,
  `Vikailmoitus_idPalautelomake` INT NOT NULL,
  `Palaute` VARCHAR(3000) NULL,
  `Siivous` TINYINT(1) NULL,
  `Kulutustavarat` TINYINT(1) NULL,
  `Varustus` TINYINT(1) NULL,
  `Kasitelty` TINYINT(1) NULL,
  `ViimeksiTallentanut` VARCHAR(45) NULL,
  `Vikailmoitus_idPalautelomake1` INT NOT NULL,
  PRIMARY KEY (`idPalautelomake`, `Vikailmoitus_idPalautelomake`),
  UNIQUE INDEX `idPalautelomake_UNIQUE` (`idPalautelomake` ASC),
  INDEX `fk_Palautelomake_Vikailmoitus1_idx` (`Vikailmoitus_idPalautelomake1` ASC),
  CONSTRAINT `fk_Palautelomake_Vikailmoitus1`
    FOREIGN KEY (`Vikailmoitus_idPalautelomake1`)
    REFERENCES `palautedb`.`Vikailmoitus` (`idPalautelomake`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `palautedb`.`Kayttaja`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `palautedb`.`Kayttaja` (
  `idKayttaja` INT NOT NULL AUTO_INCREMENT,
  `Nimi` VARCHAR(45) NULL,
  `Puhelin` VARCHAR(45) NULL,
  `email` VARCHAR(45) NOT NULL,
  `Vikailmoitus_idPalautelomake` INT NOT NULL,
  `Palautelomake_idPalautelomake` INT NOT NULL,
  `Palautelomake_Vikailmoitus_idPalautelomake` INT NOT NULL,
  PRIMARY KEY (`idKayttaja`),
  INDEX `fk_Kayttaja_Vikailmoitus1_idx` (`Vikailmoitus_idPalautelomake` ASC),
  INDEX `fk_Kayttaja_Palautelomake1_idx` (`Palautelomake_idPalautelomake` ASC, `Palautelomake_Vikailmoitus_idPalautelomake` ASC),
  CONSTRAINT `fk_Kayttaja_Vikailmoitus1`
    FOREIGN KEY (`Vikailmoitus_idPalautelomake`)
    REFERENCES `palautedb`.`Vikailmoitus` (`idPalautelomake`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Kayttaja_Palautelomake1`
    FOREIGN KEY (`Palautelomake_idPalautelomake` , `Palautelomake_Vikailmoitus_idPalautelomake`)
    REFERENCES `palautedb`.`Palautelomake` (`idPalautelomake` , `Vikailmoitus_idPalautelomake`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `palautedb`.`Tila`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `palautedb`.`Tila` (
  `idTila` INT NOT NULL AUTO_INCREMENT,
  `Nimi` VARCHAR(45) NOT NULL,
  `Vikailmoitus_idPalautelomake` INT NOT NULL,
  `Palautelomake_idPalautelomake` INT NOT NULL,
  `Palautelomake_Vikailmoitus_idPalautelomake` INT NOT NULL,
  UNIQUE INDEX `Nimi_UNIQUE` (`Nimi` ASC),
  INDEX `fk_Tila_Vikailmoitus1_idx` (`Vikailmoitus_idPalautelomake` ASC),
  INDEX `fk_Tila_Palautelomake1_idx` (`Palautelomake_idPalautelomake` ASC, `Palautelomake_Vikailmoitus_idPalautelomake` ASC),
  CONSTRAINT `fk_Tila_Vikailmoitus1`
    FOREIGN KEY (`Vikailmoitus_idPalautelomake`)
    REFERENCES `palautedb`.`Vikailmoitus` (`idPalautelomake`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Tila_Palautelomake1`
    FOREIGN KEY (`Palautelomake_idPalautelomake` , `Palautelomake_Vikailmoitus_idPalautelomake`)
    REFERENCES `palautedb`.`Palautelomake` (`idPalautelomake` , `Vikailmoitus_idPalautelomake`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
